### PR TITLE
fix(area-dialog): error message when creating area without a unique name

### LINKED ISSUE #921: No error message for duplicate Area's name
No error message for duplicate Area's name 
screenshot from 2017-04-20 17-09-59

video link: https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COQ0hiRndQNkQ4Ukk/view?usp=sharing

`{"errors":[{"code":"bad_parameter","detail":"Bad value for parameter 'name \u0026 space_id \u0026 path': 'fabric8-planner \u0026 e99e01b1-ee7a-4893-8237-cfa838622a3c \u0026 /6add3ebc-e541-48dd-90bc-894497ce008a' (expected: 'unique')","status":"400","title":"Bad parameter error"}]}
{"errors":[{"code":"unknown_error","detail":"pq: Could not complete operation in a failed transaction","status":"500","title":"Unknown error"}]}
`

### PR DESCRIPTION
**Pull request by kylebuch8**
Show an error message when a user tries to create a new area without specifying a unique area name

fixes #921

### CODE REVIEW

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-platform.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

File: src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts [hunk 1]
```diff
@@ -62,4 +70,12 @@ export class CreateAreaDialogComponent implements OnInit, OnDestroy {
   cancel() {
     this.host.close();
   }
+
+  handleError(error: any) {
+    if (error.errors[0].detail.indexOf('unique') > -1) {
```
Comment (kylebuch8) [inline src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts]: Do you want me to just update the code so we show a generic error until the API is updated to have a more specific error?

File: src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.html [hunk 2]
```diff
@@ -7,6 +7,12 @@ <h3 class="create-dialog-header">
   <section>
     <div class="form">
       <fieldset class="create-fieldset">
+        <div *ngIf="errors" class="alert alert-danger">
+          <div [hidden]="!errors.unique">
+            <span class="pficon pficon-error-circle-o"></span>
+            <strong>Unique Name</strong> A unique name is required to add a new area.
```
Comment (mindreeper2420) [inline src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.html]: change to `<b>Unique Name</b>`, as `<strong>` is a logical state and this only needs to be a physical state of the text. i.e. only bolded.

**Comment by joshuawilson** [comment]
@dgutride were you going to write up an issue for adding error codes to the API?

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by dgutride** [comment]
@joshuawilson @kylebuch8  - issue created to update the API with sufficient error information here: 
https://github.com/openshiftio/openshift.io/issues/312

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-8 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-12 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-8 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-13 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-10 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-15 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-11 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by sbose78** [comment]
@dgutride @kylebuch8 @joshuawilson 
The backend will now send a 409 if the name/hierarchy is not unique 

https://github.com/fabric8-services/fabric8-wit/pull/1509

**Comment by joshuawilson** [comment]
Thanks @sbose78, @kylebuch8 you want to try to update the PR based on the backend changes?

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-16 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-12 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by kylebuch8** [comment]
@joshuawilson - I've updated the PR for #1616 to include a check for the 409 API response.

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-17 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
Thanks @kylebuch8 
@dgutride can you please review

File: src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts [hunk 3]
```diff
@@ -4,6 +4,10 @@ import { Modal } from 'ngx-modal';
 import { Context, AreaService, Area, AreaAttributes } from 'ngx-fabric8-wit';
 import { ContextService } from '../../../shared/context.service';
 
+interface Errors {
+  unique: boolean
```
Comment (dgutride) [inline src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts]: This interface should be pulled out into the models folder.  Can you also change the name of unique to uniqueValidationFailure?  This makes it sound like it's failing because it's unique and not the other way around.

Comment (joshuawilson) [inline src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts]: or you can add the Error interface to https://github.com/fabric8-ui/fabric8-ui/tree/master/src/app/error

Comment (joshuawilson) [inline src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts]: Nevermind my comment, I was confusing errors. I agree with @dgutride that the interface should be moved to the models folder.

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-18 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io

File: src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts (hunk 3 above)
Comment (kylebuch8) [inline src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts]: @dgutride - Done! PR update is on it's way.

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1616-19 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1616-fabric8-ui.badger.fabric8.io
